-- Ștergem tabelele vechi (dacă există) pentru un setup curat
DROP TABLE IF EXISTS comenzi;
DROP TABLE IF EXISTS stoc_produse;

-- 1. Tabelul pentru comenzi (acum cu "sectiune")
CREATE TABLE comenzi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  mesa TEXT NOT NULL,
  produse JSONB NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  sectiune TEXT NOT NULL, -- Va fi 'bar' sau 'bucatarie'
  status TEXT DEFAULT 'noua' -- 'noua', 'finalizata', 'anulata'
);

-- 2. Tabelul pentru gestionarea stocului (Out of Stock)
CREATE TABLE stoc_produse (
  id_produs TEXT PRIMARY KEY, -- Corespunde cu "imageNumber" din menu.json
  epuizat BOOLEAN DEFAULT FALSE
);

-- Setăm Securitatea (RLS)
ALTER TABLE comenzi ENABLE ROW LEVEL SECURITY;
ALTER TABLE stoc_produse ENABLE ROW LEVEL SECURITY;

-- Politici Comenzi: Clienții adaugă, Staff-ul citește/modifică
CREATE POLICY "Permite adăugare comenzi publice" ON comenzi FOR INSERT WITH CHECK (true);
CREATE POLICY "Permite acces comenzi staff" ON comenzi FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Permite modificare comenzi staff" ON comenzi FOR UPDATE USING (auth.role() = 'authenticated');

-- Politici Stoc: Clienții doar citesc (ca să vadă ce e epuizat), Staff-ul modifică
CREATE POLICY "Permite citire stoc publica" ON stoc_produse FOR SELECT USING (true);
CREATE POLICY "Permite modificare stoc staff" ON stoc_produse FOR ALL USING (auth.role() = 'authenticated');

-- Activăm notificările Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE comenzi;
ALTER PUBLICATION supabase_realtime ADD TABLE stoc_produse;